### PR TITLE
Check format using tools/imports

### PR DESCRIPTION
**Pull request by calavera**
This changes the way we check the source format to use tools/imports instead of shelling out to gofmt.

TODO:

- [x] Use tools/imports rather than shelling out to gofmt.
- [x] Fetch only the pr reference rather than cloning the whole repo.
- [x] Read blob objects rather than checking out the branch and merging.
- [x] Publish commit statuses.
- [x] Remove comment warnings when the PR is mergeable and the format is correct.

### CODE REVIEW

**Comment by calavera** [comment]
I really dislike that we have a bunch of code duplicated between this project and leeroy, but I rather deal with it later if it becomes a bigger issue.

This lacks also a bunch of tests, trying to figure out if we can set the api url to use ResponseRecorder to verify that I didn't break it too much.

@jfrazelle I'd really appreciate some :eyes: on this.

**Comment by calavera** [comment]
It looks like we need to update crosbymichael/octokat in circleci, should we add a `.circle.yml` to this project?

**Comment by jfrazelle** [comment]
oh ya we could totally add a .circle.yml, I was just doing the lazy mans way

**Comment by jfrazelle** [comment]
i giess eventually we could have it all be a part of leeroy with like different config items on what to check but that can be later when we get annoyed lol

**Pull request merged**
